### PR TITLE
fix: Add HTTP status checking to fetch calls in JavaScript files

### LINKED ISSUE #506: TypeError: Node.appendChild: Argument 1 is not an object.
### Describe the issue

I get `TypeError: Node.appendChild: Argument 1 is not an object.` when trying to do a side-by-side diff between the attached `main.txt` and `fix.txt` files. (Yes, they are not I-Ds or RFCs.)

[Archive.zip](https://github.com/user-attachments/files/16244190/Archive.zip)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

### LINKED ISSUE #603: Author's Tool website requires re-browse on xml2rfc conversion failure
### Describe the issue

On https://author-tools.ietf.org/ when trying to convert a .xml XML2RFC document, if the conversion fails, I edit the document and press the "HTML" button.  I get this error: 

`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
`

To fix this, I have to re-browse for the file. When I hit "Browse", the Open File dialog opens and the name in the File Name field of the prompt is left-truncated about 15 characters for the document I'm submitting.  E.g. I see "sr-attest-02" instead of "draft-stjohns-csr-attest-02.xml".   I  have to hit the "open" button, the "cancel" button or click on the file again.  Basically, opening the Open File dialog fixes the problem regardless of what I do.

This is on windows and using Firefox 141.0, but has happened on older versions.   

To duplicate this, submit a broken document and try clicking on HTML multiple times.

### Code of Conduct

- [x] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by 1456055067**
## Summary

Users previously faced cryptic errors, such as unexpected JSON parse failures, when a server request failed. Now, response.ok checks have been added to all fetch calls before processing responses. This prevents confusing errors when the server returns non-200 HTTP status codes.

## Changes

Modified four fetch handlers to check HTTP status before processing responses:

- **main.js:** Added status checks to `render()` (line 100) and `validate()` (line 167) functions
- **iddiff.js:** Added status check to `compare()` function (line 227)
- **rfcdiff.js:** Added status check to `compare()` function (line 214)

### Issue #603 - JSON parse errors on conversion failure

**Before:** When the XML2RFC conversion failed, the JavaScript tried to parse error responses as JSON, causing:

```plain
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

Users had to browse to their file again to recover it.

**After:** When `response.ok` is false, a clear error is thrown and caught:

```plain
There was an issue processing your request. (HTTP Status: 500)
```

### Issue #506 - TypeError on large file uploads

**Before:** When users uploaded files larger than 5MB, the server returned an HTTP 413 (Payload Too Large) error. The code tried to extract a `<table>` element from the error response, causing:

```plain
TypeError: Node.appendChild: Argument 1 is not an object
```

**After:** The HTTP 413 status is detected, and a clear error message is shown to the user.

## Implementation

All changes follow the same pattern already successfully implemented in `abnf.js` (commit 5374514, PR #573):

```js
fetch(request)
    .then(function(response) {
    if (!response.ok) {
      throw new Error(`There was an issue processing your request. (HTTP Status: ${response.status})`);
    }
    return response.json(); // or response.blob()
  })
```

## Testing

- [x] Verified that all fetch handlers now have consistent error checks
- [x] Changes match the working pattern in `abnf.js`
- [x] Error messages include HTTP status codes for debugging.

## Related Issues

- Fixes #603
- Fixes #506

### CODE REVIEW

**Comment by kesara** [comment]
> Looking at test failures now

Thanks, I think those could be due to updates on `html-validate`. Tests doesn't pin a certain version, uses the latest available.

File: static/scripts/main.js [hunk 1]
```diff
@@ -97,7 +97,12 @@ function render(event) {
   });
 
   fetch(request)
-    .then(function(response) { return response.json(); })
+    .then(function(response) {
+      if (!response.ok) {
+        throw new Error(`There was an issue processing your request. (HTTP Status: ${response.status})`);
```
Comment (kesara) [inline static/scripts/main.js]: This stops from author tools displaying the error messages from the server.
The API returns non OK HTTP STATUS for errors with the JSON data that has error descriptions.
The following code portion shows those error messages:
```
      if (json.error) {
        alertError.style.display = 'block';
        messageError.innerHTML = json.error;
      }
```

**Review by kesara — CHANGES_REQUESTED** [review]
Because API returns non-200 HTTP status codes with error information, the proposed changes will stop displaying those errors.
